# Generated by Django 4.2.7 on 2025-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256, verbose_name='Слаг')),
                ('title', models.CharField(max_length=256, verbose_name='Тайтл')),
            ],
        ),
        migrations.CreateModel(
            name='TagTabacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Тайтл')),
                ('color', models.CharField(help_text='Цвет в hex', max_length=256, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Tabacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('line', models.ManyToManyField(to='main.line')),
                ('tag', models.ManyToManyField(to='main.tagtabacco')),
            ],
        ),
    ]
