# Generated by Django 4.2.7 on 2025-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tabacco_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ('order', 'title', 'slug'), 'verbose_name': 'Линейка', 'verbose_name_plural': 'Линейки'},
        ),
        migrations.AlterModelOptions(
            name='tabacco',
            options={'ordering': ('name',), 'verbose_name': 'Табак', 'verbose_name_plural': 'Табаки'},
        ),
        migrations.AlterModelOptions(
            name='tagtabacco',
            options={'ordering': ('title',), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='line',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Очередь'),
            preserve_default=False,
        ),
    ]
