# Generated by Django 4.2.7 on 2025-11-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_line_options_alter_tabacco_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('contact', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-id',),
            },
        ),
    ]
