# Generated by Django 5.2.7 on 2025-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tabacco_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='slug_china',
            field=models.CharField(default='', max_length=256, verbose_name='Слаг китайский'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='slug_eng',
            field=models.CharField(default='', max_length=256, verbose_name='Слаг английский'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='title_china',
            field=models.CharField(default='', max_length=256, verbose_name='Тайтл китайский'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='title_eng',
            field=models.CharField(default='', max_length=256, verbose_name='Тайтл английский'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabacco',
            name='description_china',
            field=models.TextField(blank=True, null=True, verbose_name='Описание китайское'),
        ),
        migrations.AddField(
            model_name='tabacco',
            name='description_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Описание английский'),
        ),
        migrations.AddField(
            model_name='tabacco',
            name='name_china',
            field=models.CharField(default='', max_length=256, verbose_name='Название китайское'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabacco',
            name='name_eng',
            field=models.CharField(default='', max_length=256, verbose_name='Название английский'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagtabacco',
            name='title_china',
            field=models.CharField(default='', max_length=256, verbose_name='Тайтл китайский'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagtabacco',
            name='title_eng',
            field=models.CharField(default='', max_length=256, verbose_name='Тайтл английский'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabacco',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
