# Generated by Django 5.2.7 on 2025-12-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_line_slug_china_line_slug_eng_line_title_china_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtabacco',
            name='text_color',
            field=models.CharField(default='', help_text='Цвет в hex', max_length=256, verbose_name='Цвет текста'),
            preserve_default=False,
        ),
    ]
