# Generated by Django 5.2.7 on 2025-12-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tagtabacco_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightTabacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Вес',
                'verbose_name_plural': 'Веса',
                'ordering': ('weight',),
            },
        ),
        migrations.AddField(
            model_name='tabacco',
            name='weight',
            field=models.ManyToManyField(to='main.weighttabacco'),
        ),
    ]
