# Generated by Django 6.0.2 on 2026-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_weighttabacco_tabacco_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabacco',
            options={'ordering': ('order',), 'verbose_name': 'Табак', 'verbose_name_plural': 'Табаки'},
        ),
        migrations.AddField(
            model_name='tabacco',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Очередь'),
        ),
    ]
