# Generated by Django 6.0.2 on 2026-03-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tabacco_options_tabacco_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название точки')),
                ('coordinate_x', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координата X')),
                ('coordinate_y', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координата Y')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('phone_number', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Точка на карте',
                'verbose_name_plural': 'Точки на карте',
                'ordering': ('-id',),
            },
        ),
    ]
