# Generated by Django 6.0.2 on 2026-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mappoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='city_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город eng'),
        ),
    ]
