# Generated by Django 6.0.2 on 2026-03-27 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_mappoint_city_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код страны')),
                ('region_group', models.CharField(blank=True, choices=[('WORLD', 'WORLD'), ('CIS', 'CIS'), ('RU', 'RU')], max_length=20, null=True, verbose_name='Группа регионов')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название eng')),
                ('name_china', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название china')),
                ('coordinate_x', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координата X')),
                ('coordinate_y', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координата Y')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Активен?', null=True, verbose_name='Активен?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания, для служебного пользования.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего изменения, для служебного пользования.', verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Информация точки',
                'verbose_name_plural': 'Информация точек',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='coordinate_x',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='coordinate_y',
        ),
        migrations.AddField(
            model_name='mappoint',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='address_china',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес china'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='address_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес eng'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='country_china',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна china'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='country_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна eng'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата создания, для служебного пользования.', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappoint',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Активен?', null=True, verbose_name='Активен?'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='is_official',
            field=models.BooleanField(blank=True, default=True, help_text='Официальный?', null=True, verbose_name='Официальный?'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='region_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата последнего изменения, для служебного пользования.', verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Веб сайт'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='ExtraContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название платформы')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные для связи')),
                ('map_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mappoint')),
            ],
            options={
                'verbose_name': 'Дополнительный контакт',
                'verbose_name_plural': 'Дополнительные контакты',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='mappoint',
            name='map_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mapinfo'),
        ),
    ]
