# Generated by Django 6.0.2 on 2026-03-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_mapinfo_remove_mappoint_coordinate_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappoint',
            old_name='map_point',
            new_name='map_info',
        ),
    ]
