# Generated by Django 6.0.2 on 2026-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_map_point_mappoint_map_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='city_china',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город china'),
        ),
    ]
