# Generated by Django 6.0.2 on 2026-03-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_mappoint_city_china'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
    ]
