# Generated by Django 6.0.2 on 2026-03-29 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_mappoint_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('country_eng', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна eng')),
                ('country_china', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна china')),
            ],
            options={
                'verbose_name': 'Страна точки',
                'verbose_name_plural': 'Страны точек',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='country_china',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='country_eng',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='is_official',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='region_group',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='website',
        ),
        migrations.AddField(
            model_name='mappoint',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='coordinate_x',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координата X'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='coordinate_y',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координата Y'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='map_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mapcountry'),
        ),
        migrations.DeleteModel(
            name='ExtraContact',
        ),
        migrations.DeleteModel(
            name='MapInfo',
        ),
    ]
