# Generated by Django 6.0.2 on 2026-03-29 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_mapcountry_remove_mappoint_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappoint',
            name='coordinate_x',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='coordinate_y',
        ),
        migrations.AddField(
            model_name='mappoint',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
