# Generated by Django 6.0.2 on 2026-03-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_mappoint_coordinate_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='soc_inst',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='soc_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' MAX'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='soc_telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='soc_vk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт'),
        ),
    ]
